// 'group-hover', 'group-focus', 'first', 'last', 'odd', 'even',
// 'hover', 'focus-within', 'focus-visible', 'motion-safe', 'motion-reduce',
// 'checked', 'focus', 'active', 'visited', 'disabled'
module.exports = {
  accessibility: ['responsive', 'focus'],
  alignContent: ['responsive'],
  alignItems: ['responsive'],
  alignSelf: ['responsive'],
  animation: ['responsive', 'hover', 'focus', 'group-hover'],
  appearance: ['responsive'],
  aspectRatio: ['responsive'],
  backgroundAttachment: ['responsive', 'hover', 'focus'],
  backgroundClip: ['responsive', 'hover', 'focus'],
  backgroundColor: [
    'responsive',
    'group-hover',
    'group-visited',
    'before',
    'after',
    'hover',
    'focus',
    'active',
    'checked',
    'odd',
    'even',
    'visited',
  ],
  backgroundImage: ['responsive', 'hover', 'focus'],
  backgroundOpacity: ['responsive', 'hover', 'focus'],
  backgroundPosition: ['responsive', 'hover', 'focus'],
  backgroundRepeat: ['responsive', 'hover', 'focus'],
  backgroundSize: ['responsive', 'hover', 'focus'],
  borderCollapse: ['responsive'],
  borderColor: ['responsive', 'hover', 'focus', 'before', 'after'],
  borderOpacity: ['responsive', 'hover', 'focus', 'before', 'after'],
  borderRadius: ['responsive', 'before', 'after', 'hover', 'focus'],
  borderStyle: ['responsive', 'before', 'after'],
  borderWidth: [
    'responsive',
    'before',
    'after',
    'first',
    'last',
    'hover',
    'focus',
    'focus-within',
  ],
  boxShadow: ['responsive', 'hover', 'focus', 'before', 'after'],
  boxSizing: ['responsive'],
  clear: ['responsive'],
  container: ['responsive'],
  cursor: ['responsive'],
  display: [
    'responsive',
    'group-checked',
    'group-hover',
    'hover',
    'checked',
    'before',
    'after',
  ],
  divideColor: ['responsive'],
  divideOpacity: ['responsive'],
  divideStyle: ['responsive'],
  divideWidth: ['responsive'],
  fill: ['responsive'],
  flex: ['responsive'],
  flexDirection: ['responsive'],
  flexGrow: ['responsive'],
  flexShrink: ['responsive'],
  flexWrap: ['responsive'],
  float: ['responsive'],
  fontFamily: ['responsive'],
  fontSize: ['responsive'],
  fontSmoothing: ['responsive'],
  fontStyle: ['responsive'],
  fontWeight: ['responsive', 'hover', 'focus'],
  gap: ['responsive'],
  gradientColorStops: ['responsive', 'hover', 'focus'],
  gridAutoFlow: ['responsive'],
  gridColumn: ['responsive'],
  gridColumnEnd: ['responsive'],
  gridColumnStart: ['responsive'],
  gridRow: ['responsive'],
  gridRowEnd: ['responsive'],
  gridRowStart: ['responsive'],
  gridTemplateColumns: ['responsive'],
  gridTemplateRows: ['responsive'],
  height: ['responsive', 'before', 'after'],
  inset: ['responsive', 'hover', 'focus', 'before', 'after', 'group-hover'],
  justifyContent: ['responsive'],
  letterSpacing: ['responsive'],
  lineHeight: ['responsive'],
  listStylePosition: ['responsive'],
  listStyleType: ['responsive'],
  margin: ['responsive', 'hover', 'focus', 'group-hover'],
  maxHeight: ['responsive'],
  maxWidth: ['responsive'],
  minHeight: ['responsive'],
  minWidth: ['responsive'],
  objectFit: ['responsive'],
  objectPosition: ['responsive'],
  opacity: [
    'responsive',
    'group-hover',
    'group-focus',
    'group-checked',
    'checked',
    'hover',
    'focus',
    'disabled',
  ],
  order: ['responsive'],
  outline: ['responsive', 'focus'],
  overflow: ['responsive'],
  overscrollBehavior: ['responsive'],
  padding: ['responsive', 'before', 'after'],
  placeholderColor: ['responsive', 'focus'],
  placeholderOpacity: ['responsive', 'focus'],
  pointerEvents: ['responsive'],
  position: ['responsive', 'group-hover', 'hover', 'focus', 'before', 'after'],
  resize: ['responsive'],
  rotate: ['responsive', 'hover', 'focus'],
  scale: ['responsive', 'hover', 'focus'],
  skew: ['responsive', 'hover', 'focus'],
  space: ['responsive'],
  stroke: ['responsive'],
  strokeWidth: ['responsive'],
  tableLayout: ['responsive'],
  textAlign: ['responsive', 'hover', 'focus'],
  textColor: [
    'responsive',
    'hover',
    'focus',
    'group-hover',
    'group-focus',
    'visited',
    'checked',
  ],
  textDecoration: ['responsive', 'hover', 'focus'],
  textOpacity: ['responsive', 'hover', 'focus'],
  textTransform: ['responsive', 'hover', 'focus'],
  transform: ['responsive', 'group-checked', 'before', 'after', 'checked'],
  transformOrigin: ['responsive', 'group-checked', 'checked'],
  transitionDelay: ['responsive', 'group-checked', 'checked'],
  transitionDuration: ['responsive', 'group-checked', 'checked'],
  transitionProperty: ['responsive', 'group-checked', 'checked'],
  transitionTimingFunction: ['responsive', 'group-checked', 'checked'],
  translate: ['responsive', 'before', 'after', 'hover', 'focus', 'motion-safe'],
  userSelect: ['responsive'],
  verticalAlign: ['responsive'],
  visibility: ['responsive'],
  whitespace: ['responsive'],
  width: ['responsive', 'before', 'after'],
  wordBreak: ['responsive'],
  zIndex: ['responsive'],
};
